### ISSUE TITLE
Missing <pb.h> when using library

### ISSUE THREAD

**Issue by mcsarge** [meshtastic/Meshtastic-arduino#19]
When including this and trying to compile I get an error that <pb.h> is not a file that is avaialble. I understand it might be from the protocol buffers, but was it inadvertently left out of the package?

![image](https://github.com/meshtastic/Meshtastic-arduino/assets/195996/4a16165d-f4e6-4d9b-beaa-1c8a557c12ea)

Matt

**Comment by caveman99** [comment]
you need to include nanopb in your arduino libs.

**Comment by mcsarge** [comment]
I am using Platformio and there is no such library. What I did do is create a folder in my /lib directory, named "nanopb" and put the base files in it from the zip folder. This is easy, but the link referenced really does not spell that out for this particular library. Do you want me to write up the procedure so you can update the docs?
