### ISSUE TITLE
How is this actually used

### ISSUE THREAD

**Issue by xznhj8129** [meshtastic/Meshtastic-arduino#24]
The examples absolutely do not clarify how to actually configure meshtastic or the device to talk, for a beginner this does not work at all
Does serial mode have to be on?
Mode default, simple, proto, textmsg?
How do i know i am actually connected to the meshtastic node, with how complex it can be to establish a simple serial connection with an ESP32 there is absolutely no indication of anything

**Comment by GUVWAF** [comment]
This repository is linked from the [Serial Module](https://meshtastic.org/docs/configuration/module/serial/#mode) page in the documentation, which states you should use it in `PROTO` mode, and yes the Serial Module needs to be enabled.

**Comment by xznhj8129** [comment]
Thank you. I seem to be afflicted with a particular curse that makes it so whatever is not working will always start working the moment after i open a github issue, like some kind of quantum observation effect. It does work with these settings.
