### ISSUE TITLE
Connect to Lora over existing Wifi

### ISSUE THREAD

**Issue by jpbusman** [meshtastic/Meshtastic-arduino#28]
Hello,

In my esp32 project there is a network connection available already with (Lora device is connected to AP too)
client = WiFi.begin(ssid, password);
this is for an API to Telegram
Connecting to a node can be done with 
client.connect(RADIO_IP, RADIO_PORT);

but this library needs to setup a connection with wifi with pins
mt_wifi_init(WIFI_CS_PIN, WIFI_IRQ_PIN, WIFI_RESET_PIN, WIFI_ENABLE_PIN, WIFI_SSID, WIFI_PASS);

How can I do the init without setting op wifi with pins and only ssid and password?

**Comment by caveman99** [comment]
This library includes a sample wifi drier for an external board connected to an Arduino. Trrhe ESP32 wifi works differently, you'd have to adapt the lib to this.
