### ISSUE TITLE
Compatibility with megaTinycore 0/1/2 series

### ISSUE THREAD

**Issue by m-anish** [meshtastic/Meshtastic-arduino#30]
This looks like a nice library. I just wanted to ask, before I spent any time on it, whether this library will work with any of the UPDI programmable 0/1/2 tinyMega series of AVR microcontrollers?

I am diy-ing a node with a nrf supermini and coresx1262 and it would be an advantage to use this over the standard TEXTMSG mode of the serial module so am exploring that possibility.

Just wondering how realistic my expectations should be. 

Thank you and have a nice day!

**Comment by todd-herbert** [comment]
I did have a go at compiling for 328p and 32u4 a few weeks ago. From what I remember, the code wouldn't quite fit in the 32k of flash (~130%).

**Comment by m-anish** [comment]
Yeah. Doesn't compile for arduino uno / atmega328p, so I guess tiny's are a no-go. Back to serial/txtmsg mode for me :)
