### ISSUE TITLE
Missing "pb.h"

### ISSUE THREAD

**Issue by HDHristov** [meshtastic/Meshtastic-arduino#4]
Hi. I'm trying to get this working, but I'm getting this error when trying to compile the GPS example code:

```
\Arduino\libraries\Meshtastic\src\mt_nanopb.h:6:10:` fatal error: pb.h: No such file or directory
    6 | #include "pb.h"
      |          ^~~~~~
compilation terminated.
```

Seems we are missing that "pb.h" or I'm missing something else.

**Comment by caveman99** [comment]
you need to add the nanopb dependency to your project. We don't bundle the needed library.
